# Generated by Django 4.2.5 on 2023-09-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheese', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheese',
            old_name='details',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cheese',
            old_name='subject',
            new_name='origin_country',
        ),
        migrations.AddField(
            model_name='cheese',
            name='type',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
    ]
